"""add_xhs_templates_and_task_fields

Revision ID: ae291010123b
Revises: 8db31ce77282
Create Date: 2026-03-12 01:31:03.148517+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ae291010123b'
down_revision: Union[str, None] = '8db31ce77282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xhs_templates',
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='模板描述'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='分类: food/fashion/travel 等'),
    sa.Column('cover_url', sa.String(length=500), nullable=True, comment='封面预览图 URL'),
    sa.Column('default_topic', sa.String(length=500), nullable=False, comment='默认主题文案'),
    sa.Column('style_prompt', sa.Text(), nullable=True, comment='AI 图片风格提示词'),
    sa.Column('page_count', sa.Integer(), nullable=False, comment='默认生成页数'),
    sa.Column('example_pages', sa.JSON(), nullable=True, comment='示例页面 (JSON)'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序权重（越大越前）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='创建者ID'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='更新者ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xhs_templates_category'), 'xhs_templates', ['category'], unique=False)
    op.create_index(op.f('ix_xhs_templates_id'), 'xhs_templates', ['id'], unique=False)
    op.create_index(op.f('ix_xhs_templates_is_active'), 'xhs_templates', ['is_active'], unique=False)
    op.alter_column('announcement_departments', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('announcement_departments', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('announcements', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('announcements', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('audit_logs', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('departments', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('departments', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('roles', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('roles', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('user_departments', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('user_departments', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('user_prompts', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('user_prompts', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.add_column('xhs_tasks', sa.Column('template_id', sa.Integer(), nullable=True, comment='使用的模板 ID'))
    op.add_column('xhs_tasks', sa.Column('copywriting', sa.JSON(), nullable=True, comment='生成的发布文案 (JSON)'))
    op.add_column('xhs_tasks', sa.Column('last_autosave_at', sa.DateTime(), nullable=True, comment='最后自动保存时间'))
    op.alter_column('xhs_tasks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('xhs_tasks', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.create_index(op.f('ix_xhs_tasks_template_id'), 'xhs_tasks', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xhs_tasks_template_id'), table_name='xhs_tasks')
    op.alter_column('xhs_tasks', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('xhs_tasks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_column('xhs_tasks', 'last_autosave_at')
    op.drop_column('xhs_tasks', 'copywriting')
    op.drop_column('xhs_tasks', 'template_id')
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('user_prompts', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('user_prompts', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('user_departments', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('user_departments', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('roles', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('roles', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('departments', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('departments', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('audit_logs', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('announcements', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('announcements', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('announcement_departments', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('announcement_departments', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_index(op.f('ix_xhs_templates_is_active'), table_name='xhs_templates')
    op.drop_index(op.f('ix_xhs_templates_id'), table_name='xhs_templates')
    op.drop_index(op.f('ix_xhs_templates_category'), table_name='xhs_templates')
    op.drop_table('xhs_templates')
    # ### end Alembic commands ###

